### ISSUE TITLE
공통컴포넌트 타입 에러

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#22]
## 🐞 버그 내용
> 어떤 버그인지 설명해주세요.

공통 컴포넌트의 타입에러

- 상수화된 타입으로 인해 동적으로 카테고리 이름을 넣게 되면 아래와 같은 에러가 뜹니다.
```
<CategoryTag category={`${problem.category}`} />
```
```
<CategoryTag category={problem.category} />
```
<img width="661" alt="Screenshot 2024-08-12 at 2 44 55 AM" src="https://github.com/user-attachments/assets/896edcf4-541a-46d5-b848-c01c0c92ae0f">
<br/>

## 🖥️ 재현 방법
> 버그가 어떤 과정을 통해 발생했는지 순서대로 작성해주세요.

<br/>
 `@/app/quiz/page.tsx`의 37번 라인

<img width="551" alt="Screenshot 2024-08-12 at 2 48 53 AM" src="https://github.com/user-attachments/assets/25c6e291-5eb1-4819-9287-3040402c6b38">

## 🪄 예상 결과
> 정상적으로 작동할 경우 어떤 결과를 예상하는지 설명해주세요.

<br/>

빨간 줄 없이 컴포넌트 정상 동작

## 📸 스크린샷

<br/>

## 📄 추가 내용

- 현재 컴포넌트 속의 텍스트나 모양은 그대로 잘 나오는 상황이기 때문에 급한 부분은 아니지만, 혹시나 놓치게 될까봐 이슈로 올립니다!

**Comment by lsy20140** [comment]
problem이라는 데이터가 어떤 형태인지 잘 모르겠지만 해당 데이터에 타입 지정이 안 되어 있어서 발생하는 오류 같습니당

**Comment by azure-553** [comment]
<img width="419" alt="Screenshot 2024-08-12 at 3 41 41 AM" src="https://github.com/user-attachments/assets/cc777083-c105-41e4-bfc6-27ebe9cc7968">

알려주신대로 타입 지정했습니다 ~ !!
